#' Import discharge data
#'
#' Imports discharge data from csv file from Stephen Wallace. Change as needed if csv format changes but ensure exported file retains specified format
#'
#' @param user_data_folder file path to user data folder
#' @param site site folder in user_data_folder
#' @note
#' All functions expect data to be in following folders:
#'
#' \describe{
#'   \item{1. user_data_folder/site/ADCP_data}{- Place 000 files here}
#'    }
#' \describe{
#'   \item{2. user_data_folder/site/Analyte_data}{- Place TSS data from EAGLE IO csv export here}
#'    }
#'    \describe{
#'   \item{3. user_data_folder/site/Channel_Geometry}{- Place cross-section survety in xs.RDS file format from Stephen Wallace here}
#'    }
#'    \describe{
#'   \item{4. user_data_folder/site/Discharge_data }{- Place discharge and velocity csv files from Stephen Wallace here}
#'    }
#'    \describe{
#'   \item{5. user_data_folder/site/Height_Offsets}{- Place height offset data from EAGLE IO csv export here}
#'    }
#'    \describe{
#'   \item{6. user_data_folder/site/Sonde_and_Height_data}{- Place TSS data from EAGLE IO csv export here}
#'    }
#'
#' Where "site" is a specific site (e.g., for Johnstone at Innisfail use site <- "JRI")
#'
#' See vignette('LinkrealTimeloads') for further instructions
#'
#' @section Warning:
#' Users can change how data is imported but should ensure outputs follow structure in rds file generated by function
#'
#' @return Discharge.rds in user_data_folder/site/Discharge_data
#' @seealso
#' \code{\link{Link_to_Real_time_loads}} Process data in specified folder structure using realTimeloads package
#' \code{\link{Predict_TSS_from_SCI}} Estimates TSS from processed acoustic backscatter and turbidit
#'
#' @author Daniel Livsey (2023) ORCID: 0000-0002-2028-6128
#' @examples
#' # See vignette('LinkrealTimeloads',package = LinkrealTimeloads)
#' @references
#' Stephen Wallace (2023, DES) provided crucial functions in Import_Channelmaster_Data() to extract data from binary 000 files.
#'
#' Livsey D.N. (2023). realTimeloads: Analyte Flux and Load from Estimates of Concentration and Discharge_. R package version 1.0.0.
#'
#' Livsey, D.N. (in review). National Industry Guidelines for hydrometric monitoring–Part 12: Application of acoustic Doppler velocity meters to measure suspended-sediment load. Bureau of Meteorology. Melbourne, Australia
#'
#' @export
Import_discharge <- function(user_data_folder,site = NULL) {

all_site_folders <- list.dirs(user_data_folder,recursive = "FALSE",full.names = TRUE)
zsites <- list.dirs(user_data_folder,recursive = "FALSE",full.names = FALSE)
# get specific site folder if site is provided
if (!is.null(site)) {
  all_site_folders <- all_site_folders[grepl(site,all_site_folders)]
  zsites <- site
}

number_of_sites <- length(all_site_folders)
Site_List <- readRDS(paste0(user_data_folder,'/Site_List.rds'))

for (k in 1:number_of_sites) {
  file <- list.files(paste0(all_site_folders[k],'/Discharge_data/'),'Q.CSV',full.names = TRUE)
  if (length(file)>0) {
  if (file.exists(file)) {


    df <- read.csv(file)
    time <- as.POSIXct(df$time,tz = "Australia/Brisbane")
    Discharge_m_cubed_per_s <- df$value_Discharge
    Site_number <- Site_List$Site_Number[grepl(zsites[k],Site_List$Site_Folder)]
    Discharge <- data.frame(time,Discharge_m_cubed_per_s,Site_number)
    RDSfile <- paste0(all_site_folders[k],'/Discharge_data/Discharge.rds')
    saveRDS(Discharge,RDSfile)
    msg <- paste0('Saved Discharge.rds file to:',paste0(all_site_folders[k],'/Discharge_data'))
  }
  }
}

return(invisible(NULL))

}
