#' Import and process data in specified folder structure using realTimeloads package
#'
#' Imports, processes, and imputes data in user_data_folder folders (see note below). Calling this function periodically will check for changes to 000 file size and will appended new data as needed. After running this function use Compute_load() (see link below)
#'
#' @param user_data_folder file path to user data folder
#' @param overwrite logical to overwrite all previous outputs
#' @param site site folder(s) under user_data_folder
#' @note
#' All functions expect data to be in following folders:
#'
#' \describe{
#'   \item{1. user_data_folder/site/ADCP_data}{- Place 000 files here}
#'    }
#' \describe{
#'   \item{2. user_data_folder/site/Analyte_data}{- Place TSS data from EAGLE IO csv export here}
#'    }
#'    \describe{
#'   \item{3. user_data_folder/site/Channel_Geometry}{- Place cross-section survety in xs.RDS file format from Stephen Wallace here}
#'    }
#'    \describe{
#'   \item{4. user_data_folder/site/Discharge_data }{- Place discharge and velocity csv files from Stephen Wallace here}
#'    }
#'    \describe{
#'   \item{5. user_data_folder/site/Height_Offsets}{- Place height offset data from EAGLE IO csv export here}
#'    }
#'    \describe{
#'   \item{6. user_data_folder/site/Sonde_and_Height_data}{- Place TSS data from EAGLE IO csv export here}
#'    }
#'
#' Where "site" is a specific site (e.g., for Johnstone at Innisfail use site <- "JRI")
#'
#' See vignette('LinkrealTimeloads') for further instructions
#'
#' @section Warning:
#' Only set overwrite = T if you understand what will happen in each function below
#'
#' See note above on file structure
#'
#' Site_list_update() and Site__and_Channel_Information_Update() must be manually updated when adding new sites
#'
#' @return Processed data in subfolders of user_data_folder
#' @seealso
#'
#' \code{\link{Compute_load}} Computes load generated by outputs from Link_to_Real_time_loads()
#'
#' @author Daniel Livsey (2023) ORCID: 0000-0002-2028-6128
#' @examples
#' # See vignette('LinkrealTimeloads',package = LinkrealTimeloads)
#' @references
#' Stephen Wallace (2023, DES) provided crucial functions in Import_Channelmaster_Data() to extract data from binary 000 files.
#'
#' Livsey D.N. (2023). realTimeloads: Analyte Flux and Load from Estimates of Concentration and Discharge_. R package version 1.0.0.
#'
#' Livsey, D.N. (in review). National Industry Guidelines for hydrometric monitoring–Part 12: Application of acoustic Doppler velocity meters to measure suspended-sediment load. Bureau of Meteorology. Melbourne, Australia
#' @export
Link_to_Real_time_loads <- function(user_data_folder,site=NULL,overwrite=FALSE) {

# warn user if overwrite is set to T
if (overwrite) {
  warning("Warning!! Overwrite = T, are you sure? Enter: yes or no")
  user_input <- readline("Warning!! Overwrite = T, are you sure? Enter: yes or no: ")
  if (user_input!="yes") {
    overwrite = FALSE # set to FALSE if user does not indicate yes
  }
}



#setwd("C:/Users/livseyd/OneDrive - Queensland University of Technology/Documents/R/LoadDashboard")
# Code to import ADCP data and process acoustic backscatter
#source('Import_Channelmaster_Data.R')
#source('Process_Backscatter.R')
#source('Concatenate_Backscatter.R')
#source('ADCP_Setting_Summary_Table.R')
# Import Eagle IO data (analyte data, datum offsets, and timeseries of height and sonde data)
#source('Import_EAGLE_IO_csv_data.R')
# Update site list and associated data frames
#source('Site__and_Channel_Information_Update.R')
#source('Site_list_update.R')
# Impute missing data
#source('Impute_height_discharge_velocity_and_conductivity.R')

# for debugging
# user_data_folder <- "C:/Users/livseyd/OneDrive - Queensland University of Technology/Documents/R/LoadDashboard/user_data"
# from_time <- as.POSIXct("2017-07-01 00:00:00 AEST")
# to_time <- as.POSIXct("2023-09-01 00:00:00 AEST")
# site=NULL
# overwrite=FALSE
# MC = 1

# Check if site list needs updating
Site_list_update(user_data_folder)

# Import Eagle IO data
# writes, Sonde.rds, Height.rds, and Height_Offsets.rds
Import_EAGLE_IO_csv_data(user_data_folder,site=site)

# Import Discharge data
Import_discharge(user_data_folder,site=site)

# Update channel geometry and ADCP location if needed
# One must manually update Site__and_Channel_Information_Update.R and xs.rds files in user_data_folder/site/Channel_Geometry if new cross-section surveys are completed and/or the ADCP changes location
Site__and_Channel_Information_Update(user_data_folder)
fileSiteList <- paste0(user_data_folder,'/Site_List.rds')
Site_List <- readRDS(fileSiteList)

# Import 000 files to R and save as rds in respective folder
# checks for changes to 000 files in all site folders in user_data_folder unless site is specified
# also writes, and if needed, updates "All_ADCP_Programming_Data.rds"
Import_Channelmaster_Data(user_data_folder,overwrite=overwrite,site=site)

# Determine periods when ADCP settings are held constant, writes "ADCP_Setting_Summary_Table.rds"
ADCP_Setting_Summary_Table(user_data_folder,site=site)

# Impute Discharge, Height, Velocity, and Specific Conductivity data, runs if duration from to_time to last time in imputed file exceeds 30 days
MC <- 1
to_time <- Sys.time()

if (!is.null(site)) {
  ADCP_Setting_Summary_Table <- readRDS(paste0(paste0(paste0(user_data_folder,'/'),site),'/ADCP_data/ADCP_Setting_Summary_Table.rds'))

  from_time <- min(ADCP_Setting_Summary_Table$Start_time[ADCP_Setting_Summary_Table$Start_time>"2005-01-01 00:00:00 AEST"])

Impute_height_discharge_velocity_and_conductivity(user_data_folder,from_time,to_time,overwrite = overwrite,MC = MC,site=site)
}

# If no site is given assume run imputation for all sites
if (is.null(site)) {
site_folders <- list.dirs(user_data_folder,recursive=FALSE,full.names = FALSE)
for (k in 1:length(site_folders)) {
  ADCP_Setting_Summary_Table <- readRDS(paste0(paste0(paste0(user_data_folder,'/'),site_folders[k]),'/ADCP_data/ADCP_Setting_Summary_Table.rds'))

  from_time <- min(ADCP_Setting_Summary_Table$Start_time[ADCP_Setting_Summary_Table$Start_time>"2005-01-01 00:00:00 AEST"])

  Impute_height_discharge_velocity_and_conductivity(user_data_folder,from_time,to_time,overwrite = overwrite,MC = MC,site=site_folders[k])

  rm(ADCP_Setting_Summary_Table)
}
}

# Process backscatter data now that height and specific conductivity has been imputed
# Processed backscatter is saved to each 000 file
Process_Backscatter(user_data_folder,overwrite=overwrite,site=site)

# Concatenate all backscatter data and write to Processed_Backscatter_data.rds
Concatenate_Backscatter(user_data_folder,site=site)

### Predict TSS from backscatter and turbidity and write to TSS_estimated_from_SCI_with_metadata.rds
Predict_TSS_from_SCI(user_data_folder,site,overwrite)

### Impute TSS using tidally filtered flow and the Froude Number
Impute_TSS(user_data_folder,site)

return(invisible('Link_to_Real_time_loads.R complete'))
}







